### ISSUE TITLE
remove binary code and add build scripts

### ISSUE THREAD

**Issue by dsvensson** [moesy/aws_lambda_ml_microservice#1]
While it's convenient to have the libraries compiled and easily available. It would be far more valuable to have the build script available so that they can be reproduced, rather than requiring the user to trust that the .so files are indeed just a compiled version of the upstream code of said version.

**Comment by moesy** [comment]
You know I forgot I had this repo public. There is a much better way to do this with a combination of Terraform and a makefile. I need to back out some things to make it universal; I will try to push it out within the next few couple of days, thanks for reminding me.

**Comment by dsvensson** [comment]
Meanwhile I would recommend that you take down these binaries though, as you're not actively updating this repository and security issues might surface over time in the versions you've built, or at least add a big fat warning on the front page "These packages don't track security patches - use at your own risk".
